---
  - name: Running terraform in plan mode
    args:
      chdir: "{{ WORKSPACE }}/terraform/aws/resources/ec2-instance"
    shell: terraform plan -var-file terrform.tfvars -out out.terraform
    become: false
    register: shell_result_plan
  - debug:
      var: terraform apply out.terraform

  - name: Running terraform in apply mode
    args:
      chdir: "{{ WORKSPACE }}/terraform/aws/resources/ec2-instance"
    shell: terraform apply out.terraform
    when: terraform apply out.terraform.rc ==0
    become: false
    register: shell_result_apply
  - debug:
      var: shell_result_apply




  


  

  
