---
  - name: Checking Terrform
    shell: which terrafrom
    become: false
    register: shell_result_check_terraform
  - debug:
      var: shell_result_check_terraform

  - name: Installing Terraform - 1
    shell: yum install -y yum-utils
    when: shell_result_check_terraform.rc != 0
    become: true
    register: shell_result_utils
  - debug:
      var: shell_result_utils

  - name: Installing Terraform - 2
    shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    when: shell_result_utils.rc == 0
    become: true
    register: shell_result_utils_2
  - debug:
      var: shell_result_utils_2

  - name: Installing Terraform - 3
    shell: yum update
    when: shell_result_utils_2.rc == 0
    become: true
    register: shell_result_utils_3
  - debug:
      var: shell_result_utils_3

  - name: Installing Terraform - 4
    shell: yum -y install terraform
    when: shell_result_utils_3.rc == 0
    become: true
    register: shell_result_utils_4
  - debug:
      var: shell_result_utils_4

  - name: Checking Terraform installation
    shell: terraform --version
    when: shell_result_utils_4.rc == 0
    become: false
    register: shell_result_check_terraform_installation
  - debug:
      var: shell_result_check_terraform_installation




  


  

  
