apiVersion: v1
kind: Secret
metadata:
  name: my-docker-hub-secret
  namespace: dev
data:
  .dockerconfigjson: ewogICAgICJhdXRocyI6IHsKICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICJhdXRoIjogIllXRnRhWEp6T21JNFpqVmpOMk15TFdNNE1UVXROR1ZoWmkxaE0yWTRMVGRtWm1NMll6WmhOelZoTWc9PSIsIAogICAgICAgICAgICAgICAiZW1haWwiOiBudWxsCiAgICAgICAgICB9CiAgICAgfQp9
type: kubernetes.io/dockerconfigjson
