---
# defaults file for myrole
DockerHub_repo: "{{ lookup('env', 'DockerHub_repo') }}"
VER: "{{ lookup('env', 'VER') }}"
user: "{{ lookup('env', 'aws_user') }}"
WORKSPACE: "{{ lookup('env', 'WORKSPACE') }}"
job: "{{ lookup('env', 'JOB') }}"
namespace: "{{ lookup('env', 'namespace') }}"
tag: "{{ lookup('env', 'tag') }}"
region: "{{ lookup('env', 'aws_region') }}" 
