---
- hosts: webservers
  remote_user: "{{ user }}"
  become: true
  become_method: sudo

  vars:
    WORKSPACE: "{{ lookup('env', 'WORKSPACE') }}"

  include_role:
    name: {{ WORKSPACE }}/ansible/roles/bastion-provision

  #roles:
  #- /root/maven-project/ansible/roles/bastion-provision
    
