---
- hosts: radical-bastion
  remote_user: "{{ user }}"
  become: true
  become_method: sudo

  vars:
    job: "{{ lookup('env', 'JOB') }}"

  roles:
    - /var/lib/jenkins/workspace/{{job}}/ansible/roles/bastion-provision
    - /var/lib/jenkins/workspace/{{job}}/ansible/roles/install-kubectl-bastion
    - /var/lib/jenkins/workspace/{{job}}/ansible/roles/deployment
   #- /root/maven-project/ansible/roles/bastion-provision
    
