---
- hosts: webservers
  remote_user: "{{ user }}"
  become: true
  become_method: sudo

  roles:
   - "/var/lib/jenkins/workspace/{{ job }}/ansible/roles/bastion-provision"
  #- /root/maven-project/ansible/roles/bastion-provision
    
