---
- hosts: webservers
  remote_user: "{{ user }}"
  become: true
  become_method: sudo

  vars:
    JOB: "{{ lookup('env', 'JOB') }}"

  roles:
    - /var/lib/jenkins/workspace/{{JOB}}/ansible/roles/deployment
   #- /root/maven-project/ansible/roles/bastion-provision
    
