---
  
  - name: Updating kubeconfig on the bastion 
    shell: aws eks update-kubeconfig --region us-west-2 --name myeks
    become: false
    register: shell_result
  - debug:
      var: shell_result
