---
- name: This sets up a Docker server
  hosts: ansibleclient1
  remote_user: ec2-user
  become: true
  become_method: sudo

  vars:
    user: ec2-user


  tasks:
  - name: Copy aws credentials
    copy:
      src: aws/credentials
      dest: /home/{{ user }}/.aws/
    register: shell_result
  - debug:
      var: shell_result

  - name: copy aws config
    copy:
      src: aws/config
      dest: /home/{{ user }}/.aws/
    register: shell_result
  - debug:
      var: shell_result

  - name: Change user perm
    args:
      chdir: /home/{{ user }}/
    shell: chown -R {{ user }}.{{ user }} .aws
    register: shell_result
  - debug:
      var: shell_result

  - name: Check aws instances
    shell: aws ec2 describe-instances
    become: false
    register: shell_result
  - debug:
      var: shell_result