---
- name: Deleting all test containers from the ansible client
  hosts: "{{ lookup('env', 'bastion_host') }}"
  remote_user: ec2-user
  become: true
  become_method: sudo

  tasks:
  
  - name: Deleting containers
    command: "{{ item }}"
    with_items: 
    - docker stop $(docker ps -a -q)
    - sleep 30
    - docker rm $(docker ps -a -q)
    - docker system prune -f
    - sleep 15
    - docker image prune --all -f
    - docker ps
    - docker ps -a
    - docker images
    register: shell_result
  - debug:
      var: shell_result


