---
- hosts: localhost
  vars:
    bastion_ip: ""
    bastion_name: "{{ lookup('env', 'bastion_name') }}"

  tasks:
  - name: Checking if radical-bastion already added to jenkins-slave host file
    shell: cat /etc/hosts | grep {{ bastion_ip }}
    register: shell_result_ip_check_slave
    ignore_errors: True
  - debug:
      var: shell_result_ip_check_slave

  - name: Adding radical-bastion to jenkins-slave host file
    shell: echo {{ bastion_ip }} {{ bastion_name }} >> /etc/hosts
    when: shell_result_ip_check_slave.rc != 0
    register: shell_result
  - debug:
      var: shell_result

  - name: Checking if radical-bastion already added to ansible hosts file 
    shell: cat /etc/ansible/hosts | grep {{ bastion_name }}
    register: shell_result_ip_check
    ignore_errors: True
  - debug:
      var: shell_result_ip_check

  - name: Adding radical-bastion to ansible hosts file
    shell: echo {{ bastion_name }} ansible_ssh_common_args=\'-o StrictHostKeyChecking=no\' >> /etc/ansible/hosts
    when: shell_result_ip_check.rc != 0
    register: shell_result
  - debug:
      var: shell_result
