---
- hosts: localhost
  vars:
    bastion_ip: ""

  tasks:
  - name: Checking if radical-bastion alsready added to ansible hosts file 
    shell: cat /etc/ansible/hosts | grep {{ bastion_ip }}
    register: shell_result_ip_check
  - debug:
      var: shell_result

  - name: Adding radical-bastion to ansible hosts file
    shell: echo {{ bastion_ip }} ansible_ssh_common_args=\'-o StrictHostKeyChecking=no\' >> /etc/ansible/hosts
    when: shell_result_ip_check.rc != 0
    register: shell_result
  - debug:
      var: shell_result
